
server:
  port: 8083
spring:
  application:
    name: microservice-user
  datasource:
    url: jdbc:mysql://localhost:3306/news?characterEncoding=utf8&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: hyy521
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/      #服务注册
  instance:
    prefer-ip-address: true         #将IP注册到服务注册中心

#放开所有节点
management:
  endpoints:
    web:
      exposure:
        include: '*'
