spring:
  application:
    name: eureka-server     #服务名称,自定义
server:
  port: 8080                #指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: false     #禁止注册自身
    fetchRegistry: false          #因为该服务没有注册到其他注册中心，所以关闭从注册中心拉取服务列表。
    #如果是服务注册中心集群，需要开启，开启就是去掉该配置，采用默认配置即可
    serviceUrl:
      #服务注册中心地址，http://账号:密码@主机名称:端口/Eureka/eureka的服务注册地址，
      #如果eureka是多节点，多个地址逗号分隔
      defaultZone: http://localhost:8080/eureka/
  server:
    renewalPercentThreshold: 0.49    #设置心跳正常的阀值，默认为1
